export type GrammarQuestion = {
  id: string
  question: string
  options: {
    A: string
    B: string
    C: string
    D: string
  }
  correctAnswer: 'A' | 'B' | 'C' | 'D'
  explanation: string
  topic: string
}

export const GRAMMAR_QUESTIONS: GrammarQuestion[] = [
  {
    id: 'q1',
    question: 'The management team recently _______ a new policy regarding remote work arrangements.',
    options: {
      A: 'approve',
      B: 'approving',
      C: 'approved',
      D: 'approves',
    },
    correctAnswer: 'C',
    explanation: 'Dấu hiệu "recently" (gần đây) đi kèm với động từ chia ở thì quá khứ đơn (hoặc hiện tại hoàn thành) để diễn tả hành động đã xảy ra. "approved" là dạng quá khứ của động từ "approve".',
    topic: 'basic-sv',
  },
  {
    id: 'q2',
    question: 'The software technicians are currently _______ the server to prevent future outages.',
    options: {
      A: 'upgraded',
      B: 'upgrading',
      C: 'upgrades',
      D: 'upgrade',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc thì hiện tại tiếp diễn: S + be (are) + currently + V-ing. Cần chọn "upgrading" đóng vai trò là hành động đang diễn ra.',
    topic: 'present-continuous',
  },
  {
    id: 'q3',
    question: 'Mr. Henderson _______ the quarterly financial report to the board of directors already.',
    options: {
      A: 'has submitted',
      B: 'submitting',
      C: 'submit',
      D: 'was submit',
    },
    correctAnswer: 'A',
    explanation: 'Có dấu hiệu "already" (đã... rồi), diễn tả hành động vừa mới hoàn thành tính đến thời điểm hiện tại. Ta chia thì hiện tại hoàn thành: S (Mr. Henderson) + has + V3 (submitted).',
    topic: 'perfect-tense',
  },
  {
    id: 'q4',
    question: '_______ you finalized the contract details with the international suppliers yet?',
    options: {
      A: 'Did',
      B: 'Have',
      C: 'Are',
      D: 'Would',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc câu hỏi thì hiện tại hoàn thành: Have/Has + S + V3 (finalized)... + yet? Chọn "Have" phù hợp với chủ ngữ "you".',
    topic: 'present-perfect-question',
  },
  {
    id: 'q5',
    question: 'The construction of the new corporate headquarters was _______ due to severe weather conditions.',
    options: {
      A: 'delayed',
      B: 'delaying',
      C: 'delay',
      D: 'delays',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc câu bị động: S + be (was) + V3 (delayed). Sự xây dựng (construction) phải "được/bị hoãn" chứ không tự hoãn.',
    topic: 'passive',
  },
  {
    id: 'q6',
    question: '_______ the invoice sent to the client via email yesterday afternoon?',
    options: {
      A: 'Has',
      B: 'Was',
      C: 'Did',
      D: 'Is',
    },
    correctAnswer: 'B',
    explanation: 'Câu hỏi bị động ở thì quá khứ đơn (có từ chỉ thời gian "yesterday"): Be (Was/Were) + S (the invoice) + V3 (sent)? Do "the invoice" là danh từ số ít nên chọn "Was".',
    topic: 'passive-question',
  },
  {
    id: 'q7',
    question: 'All employees must _______ their security badges upon entering the building.',
    options: {
      A: 'presents',
      B: 'presenting',
      C: 'present',
      D: 'presented',
    },
    correctAnswer: 'C',
    explanation: 'Cấu trúc động từ khuyết thiếu: S + modal verb (must) + V bare (động từ nguyên thể). Do đó ta chọn "present".',
    topic: 'modal',
  },
  {
    id: 'q8',
    question: 'The department head had the administrative assistant _______ the flight reservations.',
    options: {
      A: 'to confirm',
      B: 'confirmed',
      C: 'confirm',
      D: 'confirming',
    },
    correctAnswer: 'C',
    explanation: 'Cấu trúc sai khiến chủ động với Have: S + have (had) + O (người: administrative assistant) + V bare (confirm).',
    topic: 'causative-active',
  },
  {
    id: 'q9',
    question: 'The project manager got the official documents _______ by the legal department.',
    options: {
      A: 'review',
      B: 'reviewed',
      C: 'reviewing',
      D: 'to review',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc sai khiến bị động với Get: S + get + O (vật: the official documents) + V3 (reviewed). Có nghĩa là có tài liệu được xem xét bởi bộ phận pháp lý.',
    topic: 'causative-passive',
  },
  {
    id: 'q10',
    question: 'The technician _______ repaired the photocopier has been promoted to team leader.',
    options: {
      A: 'whom',
      B: 'whose',
      C: 'which',
      D: 'who',
    },
    correctAnswer: 'D',
    explanation: 'Đại từ quan hệ thay thế cho danh từ chỉ người đóng vai trò làm chủ ngữ trong mệnh đề quan hệ: N (The technician) + who + V (repaired).',
    topic: 'relative-clause',
  },
  {
    id: 'q11',
    question: 'The marketing agent _______ the presentation is the regional director.',
    options: {
      A: 'delivers',
      B: 'delivering',
      C: 'delivered',
      D: 'deliver',
    },
    correctAnswer: 'B',
    explanation: 'Rút gọn mệnh đề quan hệ dạng chủ động: N + V-ing. Câu gốc là "The marketing agent who is delivering...", rút gọn thành "delivering".',
    topic: 'reduced-active',
  },
  {
    id: 'q12',
    question: 'The items _______ to the office yesterday were damaged during transit.',
    options: {
      A: 'delivered',
      B: 'delivering',
      C: 'deliver',
      D: 'to deliver',
    },
    correctAnswer: 'A',
    explanation: 'Rút gọn mệnh đề quan hệ dạng bị động: N + V3. Câu gốc là "The items which were delivered...", rút gọn thành "delivered".',
    topic: 'reduced-passive',
  },
  {
    id: 'q13',
    question: 'The conference room is _______ small to accommodate all eighty registered delegates.',
    options: {
      A: 'so',
      B: 'such',
      C: 'too',
      D: 'enough',
    },
    correctAnswer: 'C',
    explanation: 'Cấu trúc: too + adj (small) + to V (to accommodate). Có nghĩa là phòng họp quá nhỏ để chứa đủ 80 đại biểu.',
    topic: 'too-to',
  },
  {
    id: 'q14',
    question: 'The new office space is spacious _______ to fit thirty additional workstations.',
    options: {
      A: 'enough',
      B: 'too',
      C: 'very',
      D: 'so',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc: adj (spacious) + enough + to V (to fit). Có nghĩa là văn phòng đủ rộng rãi để lắp thêm 30 bàn làm việc.',
    topic: 'enough-to',
  },
  {
    id: 'q15',
    question: 'The program is not only cost-effective _______ highly beneficial for employee morale.',
    options: {
      A: 'and also',
      B: 'but also',
      C: 'as well as',
      D: 'or else',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc liên từ tương quan: not only A + but also B (không những A mà còn B).',
    topic: 'not-only-but-also',
  },
  {
    id: 'q16',
    question: 'Applicants can choose to _______ submit their resumes online or mail them to HR.',
    options: {
      A: 'neither',
      B: 'both',
      C: 'either',
      D: 'whether',
    },
    correctAnswer: 'C',
    explanation: 'Cấu trúc liên từ tương quan: either A + or B (hoặc A hoặc B). Dấu hiệu là từ "or" phía sau.',
    topic: 'either-or',
  },
  {
    id: 'q17',
    question: '_______ the unexpected budget reductions, the project was completed on schedule.',
    options: {
      A: 'Although',
      B: 'Despite',
      C: 'Because',
      D: 'Unless',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc chỉ sự nhượng bộ đi kèm cụm danh từ: Despite / In spite of + Noun Phrase (the unexpected budget reductions). "Although" phải đi kèm một mệnh đề S+V.',
    topic: 'despite',
  },
  {
    id: 'q18',
    question: '_______ the department head was away, the assistant handled the client negotiations.',
    options: {
      A: 'Although',
      B: 'Even so',
      C: 'Despite',
      D: 'Nevertheless',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc chỉ sự nhượng bộ đi kèm mệnh đề: Although / Even though + S + V (the department head was away).',
    topic: 'although',
  },
  {
    id: 'q19',
    question: 'The earlier we submit the proposal, _______ the chances of getting approved will be.',
    options: {
      A: 'greater',
      B: 'the greatest',
      C: 'the greater',
      D: 'greatest',
    },
    correctAnswer: 'C',
    explanation: 'Cấu trúc so sánh kép: the + comparative (earlier), the + comparative (greater). Càng nộp đề án sớm, cơ hội được duyệt càng cao.',
    topic: 'the-comparative',
  },
  {
    id: 'q20',
    question: 'The supervisor provided a _______ explanation of the new filing system.',
    options: {
      A: 'detailed',
      B: 'detail',
      C: 'detailer',
      D: 'detailedly',
    },
    correctAnswer: 'A',
    explanation: 'Cần một tính từ đứng trước danh từ "explanation" để bổ nghĩa cho danh từ đó. "detailed" là tính từ (được chi tiết hóa, tỉ mỉ).',
    topic: 'word-form',
  },
  {
    id: 'q21',
    question: 'The company CEO _______ a press conference tomorrow to address the merger rumors.',
    options: {
      A: 'holds',
      B: 'will hold',
      C: 'holding',
      D: 'held',
    },
    correctAnswer: 'B',
    explanation: 'Trạng từ thời gian "tomorrow" (ngày mai) chỉ hành động sẽ xảy ra trong tương lai. Ta dùng tương lai đơn: will + hold.',
    topic: 'basic-sv',
  },
  {
    id: 'q22',
    question: 'Right now, the technicians _______ repairing the photocopier in the main lobby.',
    options: {
      A: 'be',
      B: 'are',
      C: 'is',
      D: 'was',
    },
    correctAnswer: 'B',
    explanation: 'Chủ ngữ số nhiều "the technicians" và trạng từ thời gian "right now" đi với động từ to be chia ở hiện tại tiếp diễn là "are".',
    topic: 'present-continuous',
  },
  {
    id: 'q23',
    question: 'We _______ our client list by 20% since we launched the marketing campaign.',
    options: {
      A: 'expand',
      B: 'have expanded',
      C: 'expanded',
      D: 'are expanding',
    },
    correctAnswer: 'B',
    explanation: 'Từ khóa "since" (kể từ khi) nối một mệnh đề quá khứ đơn ("since we launched...") với mệnh đề chính chia ở thì hiện tại hoàn thành (have expanded).',
    topic: 'perfect-tense',
  },
  {
    id: 'q24',
    question: 'Has the HR manager _______ the candidates for the open accountant position?',
    options: {
      A: 'interviewed',
      B: 'interview',
      C: 'interviewing',
      D: 'interviews',
    },
    correctAnswer: 'A',
    explanation: 'Câu hỏi thì hiện tại hoàn thành: Has + S + V3/ed? Chọn "interviewed" (động từ có quy tắc thêm -ed).',
    topic: 'present-perfect-question',
  },
  {
    id: 'q25',
    question: 'The annual report must be _______ by all department heads before Friday.',
    options: {
      A: 'sign',
      B: 'signing',
      C: 'signed',
      D: 'signs',
    },
    correctAnswer: 'C',
    explanation: 'Bị động với động từ khuyết thiếu: modal verb (must) + be + V3 (signed). Bản báo cáo năm cần được ký bởi các trưởng bộ phận.',
    topic: 'passive',
  },
  {
    id: 'q26',
    question: 'Was the marketing budget _______ by the chief financial officer last week?',
    options: {
      A: 'approved',
      B: 'approve',
      C: 'approving',
      D: 'approves',
    },
    correctAnswer: 'A',
    explanation: 'Câu hỏi bị động trong quá khứ: Was + S (the marketing budget) + V3 (approved) + ...?',
    topic: 'passive-question',
  },
  {
    id: 'q27',
    question: 'You should _______ the instructions carefully before assembling the desk.',
    options: {
      A: 'readed',
      B: 'reading',
      C: 'reads',
      D: 'read',
    },
    correctAnswer: 'D',
    explanation: 'Sau động từ khuyết thiếu "should" là động từ nguyên thể không "to": read.',
    topic: 'modal',
  },
  {
    id: 'q28',
    question: 'The director let the design team _______ the product layout autonomously.',
    options: {
      A: 'modify',
      B: 'modified',
      C: 'to modify',
      D: 'modifying',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc causative với "let": S + let + O (the design team) + V bare (modify). Nghĩa là cho phép nhóm thiết kế chỉnh sửa bố cục sản phẩm.',
    topic: 'causative-active',
  },
  {
    id: 'q29',
    question: 'We need to get the contract _______ by the legal department before signing.',
    options: {
      A: 'reviewing',
      B: 'review',
      C: 'reviewed',
      D: 'to review',
    },
    correctAnswer: 'C',
    explanation: 'Cấu trúc bị động: S + get + O (vật: the contract) + V3 (reviewed). Hợp đồng cần được duyệt bởi bộ phận pháp lý.',
    topic: 'causative-passive',
  },
  {
    id: 'q30',
    question: 'The customer representative _______ helped you resolve the invoice issue is no longer here.',
    options: {
      A: 'which',
      B: 'who',
      C: 'whose',
      D: 'whom',
    },
    correctAnswer: 'B',
    explanation: 'Dùng đại từ quan hệ "who" để thay thế cho danh từ chỉ người "The customer representative" làm chủ ngữ của động từ "helped".',
    topic: 'relative-clause',
  },
  {
    id: 'q31',
    question: 'The safety inspector visited the plant _______ the equipment for potential hazards.',
    options: {
      A: 'examine',
      B: 'examining',
      C: 'examined',
      D: 'examines',
    },
    correctAnswer: 'B',
    explanation: 'Rút gọn mệnh đề quan hệ dạng chủ động: N + V-ing. (Câu gốc: "...visited the plant, which was examining..." hoặc ý nghĩa chỉ mục đích chủ động của thanh tra).',
    topic: 'reduced-active',
  },
  {
    id: 'q32',
    question: 'Feedback _______ from the survey will be used to improve client relations.',
    options: {
      A: 'obtained',
      B: 'obtain',
      C: 'obtaining',
      D: 'obtains',
    },
    correctAnswer: 'A',
    explanation: 'Rút gọn mệnh đề quan hệ dạng bị động: N + V3/ed. Ý chỉ phản hồi "được thu thập" từ cuộc khảo sát (Feedback which was obtained...).',
    topic: 'reduced-passive',
  },
  {
    id: 'q33',
    question: 'The demand for the product is _______ high to fulfill with our current inventory.',
    options: {
      A: 'too',
      B: 'enough',
      C: 'very',
      D: 'so',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc: too + adj (high) + to V (to fulfill). Quá cao để có thể đáp ứng bằng kho hàng hiện tại.',
    topic: 'too-to',
  },
  {
    id: 'q34',
    question: 'Is the internet connection stable _______ to stream high-definition video?',
    options: {
      A: 'enough',
      B: 'too',
      C: 'so',
      D: 'very',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc: adj (stable) + enough + to V (to stream). Có nghĩa là mạng có đủ ổn định để phát video HD không.',
    topic: 'enough-to',
  },
  {
    id: 'q35',
    question: 'The product is neither high-quality _______ reasonably priced.',
    options: {
      A: 'nor',
      B: 'or',
      C: 'and',
      D: 'but also',
    },
    correctAnswer: 'A',
    explanation: 'Cặp liên từ tương quan phủ định: neither A + nor B (không A cũng không B).',
    topic: 'either-or',
  },
  // Subjunctive Mood (Thức giả định)
  {
    id: 'q36',
    question: 'The board of directors insisted that the chief executive officer _______ a detailed recovery plan at the next meeting.',
    options: {
      A: 'present',
      B: 'presents',
      C: 'presented',
      D: 'presenting',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc giả định với "insist that": S1 + insist + that + S2 + V-bare (động từ nguyên thể không chia). Vì vậy chọn "present".',
    topic: 'subjunctive-mood',
  },
  {
    id: 'q37',
    question: 'It is vital that all personnel _______ to the safety guidelines during the factory tour.',
    options: {
      A: 'adheres',
      B: 'adhere',
      C: 'adhered',
      D: 'adhering',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc giả định với tính từ khẩn thiết: It is vital/essential/important + that + S + V-bare. Chọn "adhere" ở dạng nguyên thể không chia.',
    topic: 'subjunctive-mood',
  },
  {
    id: 'q38',
    question: 'The auditor recommended that the finance department _______ all transaction records from the past fiscal year.',
    options: {
      A: 'reconcile',
      B: 'reconciles',
      C: 'reconciled',
      D: 'reconciling',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc giả định với "recommend that": S1 + recommend + that + S2 + V-bare. Chọn động từ nguyên thể "reconcile" (đối chiếu).',
    topic: 'subjunctive-mood',
  },
  {
    id: 'q39',
    question: 'The corporate policy mandates that every new employee _______ a comprehensive training session during their first week.',
    options: {
      A: 'completing',
      B: 'completes',
      C: 'complete',
      D: 'completed',
    },
    correctAnswer: 'C',
    explanation: 'Cấu trúc giả định với động từ mang tính bắt buộc: S1 + mandate/require + that + S2 + V-bare. Chọn động từ nguyên thể "complete".',
    topic: 'subjunctive-mood',
  },
  {
    id: 'q40',
    question: 'The legal counsel requested that the contract negotiations _______ until further review is completed.',
    options: {
      A: 'be suspended',
      B: 'are suspended',
      C: 'suspend',
      D: 'suspending',
    },
    correctAnswer: 'A',
    explanation: 'Cấu trúc giả định ở dạng bị động: S1 + request + that + S2 + be + V3 (be suspended). Các cuộc thương lượng hợp đồng phải "được tạm hoãn".',
    topic: 'subjunctive-mood',
  },
  {
    id: 'q41',
    question: 'It is highly recommended that the marketing team _______ the promotional strategy in response to competitor pricing.',
    options: {
      A: 'modifies',
      B: 'modify',
      C: 'modified',
      D: 'modifying',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc giả định dạng: It is recommended that + S + V-bare. Chọn động từ nguyên thể không chia "modify".',
    topic: 'subjunctive-mood',
  },
  // Conditional Inversion (Đảo ngữ câu điều kiện)
  {
    id: 'q42',
    question: '_______ the shipping department encounter any delays, please notify the customer service team immediately.',
    options: {
      A: 'Should',
      B: 'Had',
      C: 'Were',
      D: 'If only',
    },
    correctAnswer: 'A',
    explanation: 'Đảo ngữ câu điều kiện loại 1: Should + S + V-bare (Should the shipping department encounter... = If the shipping department encounters...).',
    topic: 'conditional-inversion',
  },
  {
    id: 'q43',
    question: '_______ we known that the seminar was fully booked, we would have registered much earlier.',
    options: {
      A: 'Should',
      B: 'Were',
      C: 'Had',
      D: 'Did',
    },
    correctAnswer: 'C',
    explanation: 'Đảo ngữ câu điều kiện loại 3 (quá khứ, giả định không có thật): Had + S + V3 (Had we known... = If we had known...). Vế sau có "would have registered".',
    topic: 'conditional-inversion',
  },
  {
    id: 'q44',
    question: '_______ the company to expand its operations overseas, it would require substantial capital investment.',
    options: {
      A: 'Should',
      B: 'Were',
      C: 'Had',
      D: 'If',
    },
    correctAnswer: 'B',
    explanation: 'Đảo ngữ câu điều kiện loại 2 (giả định không có thật ở hiện tại): Were + S + to-V (Were the company to expand... = If the company expanded...).',
    topic: 'conditional-inversion',
  },
  {
    id: 'q45',
    question: '_______ there be any further adjustments to the budget, we will issue an updated report tomorrow.',
    options: {
      A: 'Should',
      B: 'Had',
      C: 'Were',
      D: 'Unless',
    },
    correctAnswer: 'A',
    explanation: 'Đảo ngữ câu điều kiện loại 1: Should + S + V-bare (Should there be... = If there are...). Dùng động từ nguyên mẫu "be".',
    topic: 'conditional-inversion',
  },
  {
    id: 'q46',
    question: '_______ the negotiation team accepted the final terms, the merger would have been completed by now.',
    options: {
      A: 'Should',
      B: 'Were',
      C: 'Had',
      D: 'Provided',
    },
    correctAnswer: 'C',
    explanation: 'Đảo ngữ câu điều kiện loại 3: Had + S + V3 (Had the negotiation team accepted...). Vế sau dùng "would have been completed".',
    topic: 'conditional-inversion',
  },
  {
    id: 'q47',
    question: '_______ you to experience any technical difficulties, our online support desk is available 24/7.',
    options: {
      A: 'Should',
      B: 'Were',
      C: 'Had',
      D: 'If',
    },
    correctAnswer: 'B',
    explanation: 'Đảo ngữ câu điều kiện loại 2: Were + S + to-V (Were you to experience... = If you experienced...).',
    topic: 'conditional-inversion',
  },
  // Advanced Connectors (Liên từ & Giới từ nâng cao)
  {
    id: 'q48',
    question: 'The firm will proceed with the software integration project _______ that we receive client approval by Friday.',
    options: {
      A: 'provided',
      B: 'barring',
      C: 'in light of',
      D: 'notwithstanding',
    },
    correctAnswer: 'A',
    explanation: 'Cụm liên từ "provided that" hoặc "providing that" có nghĩa là "miễn là / với điều kiện là" đi kèm một mệnh đề (provided that we receive...).',
    topic: 'advanced-connectors',
  },
  {
    id: 'q49',
    question: 'The construction of the residential complex will be completed on schedule, _______ any unexpected weather disruptions.',
    options: {
      A: 'provided that',
      B: 'barring',
      C: 'given that',
      D: 'assuming',
    },
    correctAnswer: 'B',
    explanation: 'Giới từ "barring" có nghĩa là "trừ khi / ngoại trừ" đi kèm với một cụm danh từ (barring any unexpected weather disruptions).',
    topic: 'advanced-connectors',
  },
  {
    id: 'q50',
    question: '_______ the recent decline in sales, the board decided to increase the marketing budget significantly.',
    options: {
      A: 'In light of',
      B: 'Although',
      C: 'Providing that',
      D: 'Whereas',
    },
    correctAnswer: 'A',
    explanation: 'Cụm giới từ "in light of" có nghĩa là "sau khi xem xét / bởi vì" đi kèm một cụm danh từ (In light of the recent decline in sales...).',
    topic: 'advanced-connectors',
  },
  {
    id: 'q51',
    question: 'The project will be delivered successfully _______ the team remains focused and meets all deadlines.',
    options: {
      A: 'barring',
      B: 'assuming that',
      C: 'in spite of',
      D: 'notwithstanding',
    },
    correctAnswer: 'B',
    explanation: 'Liên từ "assuming that" có nghĩa là "giả định rằng / miễn là" đi kèm một mệnh đề hoàn chỉnh (assuming that the team remains focused...).',
    topic: 'advanced-connectors',
  },
  {
    id: 'q52',
    question: '_______ the fierce competition in the tech industry, our startup managed to capture a significant market share.',
    options: {
      A: 'Even though',
      B: 'Notwithstanding',
      C: 'Provided that',
      D: 'As long as',
    },
    correctAnswer: 'B',
    explanation: 'Giới từ "notwithstanding" có nghĩa là "bất kể / mặc dù" đi kèm một cụm danh từ (Notwithstanding the fierce competition...). Nó tương tự như "despite".',
    topic: 'advanced-connectors',
  },
  {
    id: 'q53',
    question: 'We will finalize the purchase order tomorrow _______ we receive a competitive quote from the vendor today.',
    options: {
      A: 'barring',
      B: 'given',
      C: 'providing that',
      D: 'in spite of',
    },
    correctAnswer: 'C',
    explanation: 'Liên từ "providing that" (miễn là) đi kèm mệnh đề (providing that we receive...).',
    topic: 'advanced-connectors',
  },
  // Participle Adjectives (Bẫy Phân từ làm tính từ)
  {
    id: 'q54',
    question: 'The company sent a personalized thank-you letter to all of its _______ clients.',
    options: {
      A: 'valuing',
      B: 'valued',
      C: 'value',
      D: 'valuablely',
    },
    correctAnswer: 'B',
    explanation: 'Dạng phân từ bị động "valued" làm tính từ đứng trước danh từ "clients" (valued clients: khách hàng được quý trọng, khách hàng VIP).',
    topic: 'participle-adjectives',
  },
  {
    id: 'q55',
    question: 'Software development is a highly _______ career that attracts creative problem-solvers.',
    options: {
      A: 'demanded',
      B: 'demanding',
      C: 'demand',
      D: 'demands',
    },
    correctAnswer: 'B',
    explanation: 'Dạng phân từ chủ động "demanding" làm tính từ mang nghĩa "đầy thách thức, đòi hỏi khắt khe" để bổ nghĩa cho danh từ "career" (a demanding career).',
    topic: 'participle-adjectives',
  },
  {
    id: 'q56',
    question: 'The HR director congratulated the marketing team on their _______ success in the campaign.',
    options: {
      A: 'outstanding',
      B: 'outstood',
      C: 'outstand',
      D: 'outstandings',
    },
    correctAnswer: 'A',
    explanation: 'Tính từ phân từ chủ động "outstanding" mang nghĩa "nổi bật, xuất chúng" bổ nghĩa cho "success" (outstanding success).',
    topic: 'participle-adjectives',
  },
  {
    id: 'q57',
    question: 'All employees found the new interactive training seminars extremely _______.',
    options: {
      A: 'rewarded',
      B: 'rewarding',
      C: 'reward',
      D: 'rewards',
    },
    correctAnswer: 'B',
    explanation: 'Cấu trúc "find something + Adj". Cần tính từ phân từ chủ động "rewarding" (mang lại cảm giác bổ ích, đáng giá) để mô tả tính chất của buổi hội thảo "training seminars".',
    topic: 'participle-adjectives',
  },
  {
    id: 'q58',
    question: 'The legal team had to review the _______ regulations before submitting the appeal.',
    options: {
      A: 'complicating',
      B: 'complicated',
      C: 'complicate',
      D: 'complicately',
    },
    correctAnswer: 'B',
    explanation: 'Cần tính từ phân từ bị động "complicated" mang nghĩa "phức tạp, rắc rối" để bổ nghĩa cho danh từ "regulations" (complicated regulations).',
    topic: 'participle-adjectives',
  },
  {
    id: 'q59',
    question: 'The corporate merger presents several _______ opportunities for career growth.',
    options: {
      A: 'promised',
      B: 'promising',
      C: 'promise',
      D: 'promises',
    },
    correctAnswer: 'B',
    explanation: 'Cần tính từ phân từ chủ động "promising" mang nghĩa "đầy hứa hẹn, đầy triển vọng" để bổ nghĩa cho danh từ "opportunities" (promising opportunities).',
    topic: 'participle-adjectives',
  },
  {
    id: 'q60',
    question: 'The newly hired supervisor has a _______ style of leadership that emphasizes collaboration.',
    options: {
      A: 'distinguished',
      B: 'distinguishing',
      C: 'distinguish',
      D: 'distinguishes',
    },
    correctAnswer: 'A',
    explanation: 'Cần tính từ phân từ bị động "distinguished" mang nghĩa "kiệt xuất, ưu tú, khác biệt" để bổ nghĩa cho danh từ "style" (a distinguished style).',
    topic: 'participle-adjectives',
  },
]

